AvivaFizzBuzzNeilAllen/Controllers/FizzBuzzBasicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AvivaFizzBuzzNeilAllen.Models;

namespace AvivaFizzBuzzNeilAllen.Controllers
{
    public class FizzBuzzBasicController : Controller
    {
        // GET: FizzBuzzBasic
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult FizzBuzzList(FizzBuzz model)
        {
            if (ModelState.IsValid)
            {
                string Fizz = "fizz";
                string Buzz = "buzz";

                if (DateTime.Now.DayOfWeek.ToString() == "Wednesday")
                {
                    Fizz = "wizz";
                    Buzz = "wuzz";
                }

                model.FizzBuzzList = new string[model.BasicValue];
                
                for (int i = 1; i <= model.BasicValue; i++)
                {
                    if (i % 3 == 0 && i % 5 == 0)
                    {
                        model.FizzBuzzList[i - 1] = Fizz + Buzz;
                    }
                    else if (i % 3 == 0)
                    {
                        model.FizzBuzzList[i - 1] = Fizz;
                    }
                    else if (i % 5 == 0)
                    {
                        model.FizzBuzzList[i - 1] = Buzz;
                    }
                    else
                    {
                        model.FizzBuzzList[i - 1] = i.ToString();
                    }
                }
                return View(model);
            }
            return RedirectToAction("Index");                                  
        }
    }
}

AvivaFizzBuzzNeilAllen/Views/FizzBuzzBasic/BasicFizzBuzz.cshtml
@model AvivaFizzBuzzNeilAllen.Models.FizzBuzz

@{
    ViewBag.Title = "BasicFizzBuzz";
}

<h2>BasicFizzBuzz</h2>

@Html.DisplayFor(model => model.BasicValue)

<ul>
    @for (int i = 0; i <= Model.BasicValue; i++)
    {
        <li>i</li>
    }
</ul>

AvivaFizzBuzzNeilAllen/Views/FizzBuzzBasic/FizzBuzzList.cshtml
@model AvivaFizzBuzzNeilAllen.Models.FizzBuzz

<style>
    .fizz {
        color: blue;
    } 
    .buzz{
        color:green;
    }
</style>

@{
    ViewBag.Title = "Fizz Buzz List";
}

<h2>Fizz Buzz List</h2>

<ol>
    @foreach (string FBValue in Model.FizzBuzzList)
    {
         <li class="@IsFizzOrBuzz(FBValue)">@Html.Label(FBValue)</li>
    }
</ol>

@functions {
    public static string IsFizzOrBuzz(string FizzBuzzValue)
    {
        if (FizzBuzzValue == "fizz" || FizzBuzzValue == "buzz")
        {
            return FizzBuzzValue;
        }
        return null;
    }
}

AvivaFizzBuzzNeilAllen/Views/FizzBuzzBasic/Index.cshtml
@model AvivaFizzBuzzNeilAllen.Models.FizzBuzz

@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Welcome";
}

<h3>Welcome to Fizz Buzz</h3>

@using (Html.BeginForm("FizzBuzzList", "FizzBuzzBasic", FormMethod.Post))
{
    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Please Enter a Value:", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BasicValue, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BasicValue, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Fizz Buzz" class="btn btn-default" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}